rules:
  # [2022.11.28] Ignore "slave"/"master" - The relation with Jenkins charm is using this
  # terminology due to support for older versions of Jenkins.
  - name: slave
  - name: master
  # Ignore whitelist - we are using it to ignore pydantic in pyptoject.toml
  - name: whitelist
