# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
options:
  jenkins_url:
    type: string
    default: ""
    description: |
      Configure the agent to use an explicit Jenkins instead of using
      the jenkins-agent relation. This allows the agent to connect to a Jenkins instance not
      managed by Juju.
  jenkins_agent_name:
    type: string
    default: ""
    description: |
      Agent name as configured in Jenkins. Multiple names can be input by using `:` as a separator.
      Example: "agent-one:agent-two:agent-three"
  jenkins_agent_token:
    type: string
    default: ""
    description: |
      Agent token provided by Jenkins. Can be found in your Jenkins instance at
      ${JENKINS_URL}/computer/${AGENT_NAME}/. Multiple tokens can be input by
      using `:` as a separator matching the order of the agents in `jenkins_agent_name`.
      Example: "token-one:token-two:token-three"
  jenkins_agent_labels:
    type: string
    default: ""
    description: |
      Comma-separated list of labels to be assigned to the agent in Jenkins. If not set it will
      default to the agents hardware identifier, e.g.: 'x86_64'
