options:
  image:
    type: string
    default: "jenkins-slave-operator"
    description: "The docker image to install. Required. Defaults to jenkins-slave-operator from rocks.canonical.com"
  tools:
    type: string
    default: git gcc make bzr
    description: Tooling to deploy on jenkins slave node
  labels:
    type: string
    description: Jenkins labels to associate with jenkins slave node
    default: ""
  jenkins_master_url:
    type: string
    default: ""
    description: |
      Configure the slave to use an explicit jenkins master instead of using
      the jenkins-slave relation. This allows for the slave and master to
      be deployed in different environments.
  jenkins_agent_name:
    type: string
    default: ""
    description: |
      Jenkins agent name that will be seen on the jenkins master.
      Will default to the hostname of the container.
  jenkins_api_token:
    type: string
    default: ""
    description: "Jenkins API token used to join the master"
  jenkins_user:
    type: string
    default: "admin"
    description: "Jenkins user to download agent.jar from master"
