name: Tests

on:
  pull_request:

jobs:
  unit-tests:
    permissions:
      contents: read
      pull-requests: write
    uses: canonical/operator-workflows/.github/workflows/test.yaml@main
    secrets: inherit
    with:
      with-uv: true
